services:
  pgdb:
    image: postgres:17
    restart: unless-stopped 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/api/router/user/user.sql:/docker-entrypoint-initdb.d/1-user.sql
      - ./backend/api/router/cat/cat.sql:/docker-entrypoint-initdb.d/2-cat.sql
      - ./backend/api/router/comment/comment.sql:/docker-entrypoint-initdb.d/3-comment.sql


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - BASE_DIR=/app
    #  - FILES_DIR=/app/files
    #volumes:
    #  - ./files:/app/files

  #frontend:

volumes:
  pgdata: